import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    height: '92%',
    marginVertical: 10,
    width: 185,
    backgroundColor: '#B00814',
    color: 'white',
    marginHorizontal: 4,
    borderRadius: 7,
    justifyContent: 'space-around',
    shadowColor: 'black',
    shadowOffset: {width: 2, height: 2},
    shadowOpacity: 0.8,
    shadowRadius: 2,
  },
  text: {
    color: 'white',
    alignSelf: 'center',
    fontWeight: 'bold',
    fontSize: 16,
  },
  plusButton: {color: 'white', fontSize: 36},
  button: {
    width: 70,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#C4444D', // Semi-transparent blue background
    borderRadius: 35,
    borderWidth: 0.1,
    alignSelf: 'center',
    opacity: 0.7,
    zIndex: 99,
    shadowColor: 'black',
    shadowOffset: {width: 2, height: 2},
    shadowOpacity: 0.8,
    shadowRadius: 2,
    backdropFilter: 'blur',
  },
  containerButton: {
    height: '100%',
    width: 185,
    backgroundColor: '#B00814',
    color: 'white',
    borderRadius: 7,
    justifyContent: 'space-around',
    shadowColor: 'black',
    shadowOffset: {width: 2, height: 2},
    shadowOpacity: 0.8,
    shadowRadius: 2,
  },
  textStyle: {color: 'white', fontSize: 36},
  textNonImage: {
    color: 'white',
    alignSelf: 'center',
  },
  buttonNonImage: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#C4444D', // Semi-transparent blue background
    borderRadius: 25,
    borderWidth: 0.1,
    position: 'absolute',
    right: 38,
    bottom: 80,
    opacity: 1,
    zIndex: 99,
  },
  image: {
    height: 80,
    width: 80,
    borderRadius: 17,
    borderColor: 'white',
    borderWidth: 0.1,
    alignSelf: 'center',
    shadowColor: 'black',
    shadowOffset: {width: -2, height: -2},
    shadowOpacity: 0.8,
    shadowRadius: 2,
  },
});
