import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
  header: {
    height: '17%',
    width: '110%',
    paddingHorizontal: '6%',
    paddingVertical: '3%',
    backgroundColor: 'white',
    alignSelf: 'center',
    justifyContent: 'space-around',
  },
  headerTextContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: '40%',
    width: '100%',
    paddingRight: '6%',
  },

  searchBarContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  count: {
    fontSize: 22,
    color: 'grey',
  },
  filterButton: {
    borderRadius: 30, // Use a larger value for more rounded corners
    height: 50,
    width: 50,
    backgroundColor: '#ECECEC',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: 'black',
    shadowOffset: {height: 2, width: 2},
    shadowRadius: 2,
    shadowOpacity: 0.4,
  },
  searchBar: {
    height: '100%',
    width: '83%',
    borderWidth: 0.1,
    borderColor: 'black',
    fontSize: 20,
    padding: 10,
    backgroundColor: '#ECECEC',
    borderRadius: 7,
    shadowColor: 'black',
    shadowOffset: {width: 2, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBlockColor: 'black',
  },
  search: {
    fontSize: 18,
    width: '80%',
  },
  headerText: {
    height: '100%',
    width: '100%',
    fontSize: 30,
    fontWeight: 'bold',
  },
});
