import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    height: '92%',
    marginVertical: 10,
    marginHorizontal: 4,
    width: 185,
    backgroundColor: '#221E1F',
    color: 'white',
    borderRadius: 7,
    justifyContent: 'space-around',
    padding: 10,
    shadowColor: 'black',
    shadowOffset: {width: 2, height: 2},
    shadowOpacity: 0.8,
    shadowRadius: 2,
  },
  textContainer: {flexDirection: 'row', alignSelf: 'center'},
  text: {
    color: 'white',
    alignSelf: 'center',
    fontWeight: 'bold',
    fontSize: 14,
  },
  simpleText: {
    color: 'white',
  },
  button: {
    width: 45,
    height: 45,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 25,
    borderWidth: 0.1,
    position: 'absolute',
    right: 35,
    bottom: 75,
    opacity: 1,
    zIndex: 99,
    shadowColor: 'black',
    shadowOffset: {width: 2, height: 2},
    shadowOpacity: 0.8,
    shadowRadius: 2,
  },
  nonImageButton: {
    color: 'white',
    alignSelf: 'center',
    height: 70,
    width: 70,
    borderRadius: 35,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  image: {
    height: 80,
    width: 80,
    borderRadius: 17,
    borderColor: 'white',
    borderWidth: 0.09,
    alignSelf: 'center',
    shadowColor: 'black',
    shadowOffset: {width: -2, height: -2},
    shadowOpacity: 0.8,
    shadowRadius: 2,
  },
});
